name: CI
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: 0 0 * * 0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Packages
        run: npm install

      - name: Lint
        run: npm run lint

  test:
    name: Test (Node@${{ matrix.node }} - ESLint@${{ matrix.eslint }} - ${{ matrix.os }})
    strategy:
      matrix:
        eslint: [6]
        node: [8, 10, 12, 14, 16, 18]
        os: [ubuntu-latest]
        include:
          # On other platforms
          - os: windows-latest
            eslint: 6
            node: 18
          - os: macos-latest
            eslint: 6
            node: 18
          # On the minimum supported ESLint/Node.js version
          - eslint: 6.6.0
            node: 8.10.0
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node@${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Packages
        run: npm install

      # - name: Install ESLint@${{ matrix.eslint }}
      #   run: npm install eslint@${{ matrix.eslint }}

      - name: Test
        run: npm run test

      # - name: Send Coverage
      #   run: npm run -s codecov
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
